# Пароль БД будет находиться в secret-объекте
# Текст секрета закодирован по 64-основанию
# Чтобы раскодировать используй `echo ZXhwZWxsaWFybXVzCg== | base64 -d`
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  password: ZXhwZWxsaWFybXVzCg==
